import { Hono } from "hono";
import type { Lifecoach } from "@lifecoach/core";
import { backfillFromCsv, parseMonarchCsv, computeNetWorth, buildMtdRollup } from "@lifecoach/core";
import { FINANCE_EVIDENCE_REF_TYPES } from "@lifecoach/schemas";

const accountsWithNetWorth = (lc: Lifecoach) => {
  const accounts = lc.storage.financial.listAccounts({ status: "active" });
  return { accounts, ...computeNetWorth(accounts) };
};

/** Read-only views over synced Monarch data, backing the Finances page. */
export const financialRoutes = (lc: Lifecoach) => {
  const app = new Hono();

  app.get("/accounts", (c) => c.json(accountsWithNetWorth(lc)));

  app.get("/net-worth", (c) => {
    const { totalAssets, totalLiabilities, netWorth } = accountsWithNetWorth(lc);
    return c.json({ totalAssets, totalLiabilities, netWorth });
  });

  app.get("/transactions", (c) => {
    const q = (k: string) => c.req.query(k);
    const limit = Math.min(Number(q("limit") ?? "50") || 50, 500);
    const transactions = lc.storage.financial
      .queryTransactions({
        ...(q("from") ? { from: Number(q("from")) } : {}),
        ...(q("to") ? { to: Number(q("to")) } : {}),
        ...(q("category") ? { category: q("category") as string } : {}),
        ...(q("accountId") ? { accountId: q("accountId") as string } : {}),
      })
      .slice(0, limit);
    return c.json({ transactions });
  });

  app.get("/budgets", (c) => {
    const month = c.req.query("month") || undefined;
    return c.json({ budgets: lc.storage.financial.listBudgets(month) });
  });

  app.get("/holdings", (c) => {
    const all = lc.storage.financial.queryHoldings();
    // Latest snapshot only (sync appends a new dated snapshot each run).
    const latest = all.reduce((m, h) => Math.max(m, h.snapshotDate), 0);
    const holdings = all.filter((h) => h.snapshotDate === latest);
    const marketValue = holdings.reduce((s, h) => s + (h.marketValue ?? 0), 0);
    const costBasis = holdings.reduce((s, h) => s + (h.costBasis ?? 0), 0);
    return c.json({ holdings, marketValue, costBasis, gain: marketValue - costBasis });
  });

  // Financial insights are now the finance-tagged SUBSET of unified inbox
  // insights (generated by the single Insighter). This means insights here
  // carry the full Inbox lifecycle (Discuss / Acted / Dismiss / Snooze), and
  // an insight that cites both finance and health evidence appears in both
  // places — which is the cross-domain reasoning the unification enables.
  app.get("/insights", (c) => {
    const all = lc.storage.insights.list({ state: "active", limit: 1000 });
    const insights = all.filter((i) =>
      i.evidenceRefs.some((ref) => FINANCE_EVIDENCE_REF_TYPES.has(ref.refType)),
    );
    return c.json({ insights });
  });

  /**
   * Month-to-date savings rate: (income − expenses) / income × 100.
   *
   * Transfer transactions are excluded via the same `isTransferTxn` cascade
   * used by the agent's `financial_monthly_rollup` tool — ensuring the UI and
   * agent always agree on the number.
   *
   * Returns `savingsRate: null` when income ≤ 0 (not enough income data yet)
   * so the UI can show "—" rather than a misleading 0 %.
   */
  app.get("/savings-rate-mtd", (c) => {
    const now = Date.now();
    const startOfMonth = (() => {
      const d = new Date(now);
      return new Date(d.getFullYear(), d.getMonth(), 1, 0, 0, 0).getTime();
    })();
    const transactions = lc.storage.financial.queryTransactions({
      from: startOfMonth,
      to: now,
    });
    const rollup = buildMtdRollup(transactions, now);
    return c.json({
      income: rollup.income,
      expenses: rollup.expenses,
      savingsRate: rollup.income > 0 ? rollup.savingsRate : null,
      daysInWindow: rollup.daysInWindow,
    });
  });

  /**
   * One-time historical backfill from a Monarch CSV export. Multipart upload
   * with field "file". Only seeds rows OLDER than the live 90-day sync window;
   * deterministic synthetic external IDs mean re-uploading the same export
   * upserts zero new rows.
   */
  app.post("/backfill", async (c) => {
    const form = await c.req.formData();
    const file = form.get("file");
    if (!file || typeof file === "string") {
      return c.json({ error: "no_file" }, 400);
    }
    const text = await (file as File).text();
    const parsed = parseMonarchCsv(text);
    if (parsed.rows.length === 0) {
      return c.json(
        {
          error: "no_rows_parsed",
          totalRows: parsed.totalRows,
          skipped: parsed.skipped,
          hint: "Expected Monarch transaction-export CSV with at least Date and Amount columns.",
        },
        400,
      );
    }
    const result = backfillFromCsv(lc.storage, parsed.rows);
    return c.json({
      result: { ...result, skippedRows: parsed.skipped },
    });
  });

  return app;
};
